import { VehicleOption, PopularLocation } from "@/types/ride";

export const VEHICLE_OPTIONS: VehicleOption[] = [
  {
    id: "rapido-bike",
    name: "Bike Taxi",
    category: "bike",
    brandTag: "Express",
    tagColor: "text-zinc-300",
    tagBg: "bg-zinc-800/80 border-zinc-700/60",
    description: "Agile solo travel with helmet provided; fastest in peak traffic",
    baseFare: 29,
    perKmRate: 9,
    perMinuteRate: 1.2,
    etaMinutes: 2,
    capacity: 1,
    iconName: "Bike",
    badge: "Fastest Pickup",
    popular: true,
  },
  {
    id: "nex-auto",
    name: "Auto Rickshaw",
    category: "auto",
    brandTag: "City",
    tagColor: "text-zinc-300",
    tagBg: "bg-zinc-800/80 border-zinc-700/60",
    description: "Direct door-to-door city commute with digital metered fares",
    baseFare: 40,
    perKmRate: 14,
    perMinuteRate: 1.5,
    etaMinutes: 3,
    capacity: 3,
    iconName: "Zap",
    badge: "Budget Saver",
  },
  {
    id: "uber-go",
    name: "Comfort Mini",
    category: "mini",
    brandTag: "Standard",
    tagColor: "text-zinc-300",
    tagBg: "bg-zinc-800/80 border-zinc-700/60",
    description: "Compact climate-controlled hatchback for everyday commute",
    baseFare: 80,
    perKmRate: 17,
    perMinuteRate: 2,
    etaMinutes: 4,
    capacity: 4,
    iconName: "Car",
    badge: "Most Popular",
    popular: true,
  },
  {
    id: "ola-prime-sedan",
    name: "Executive Sedan",
    category: "sedan",
    brandTag: "Premium",
    tagColor: "text-emerald-300",
    tagBg: "bg-emerald-950/40 border-emerald-800/50",
    description: "Premium sedan with extra legroom, quiet cabin & top chauffeurs",
    baseFare: 110,
    perKmRate: 21,
    perMinuteRate: 2.5,
    etaMinutes: 5,
    capacity: 4,
    iconName: "CarFront",
    badge: "Top Chauffeurs",
  },
  {
    id: "ola-electric",
    name: "Nex Electric EV",
    category: "ev",
    brandTag: "Eco",
    tagColor: "text-emerald-300",
    tagBg: "bg-emerald-950/40 border-emerald-800/50",
    description: "100% zero-emission electric sedan with ultra-quiet ride",
    baseFare: 95,
    perKmRate: 19,
    perMinuteRate: 2.2,
    etaMinutes: 4,
    capacity: 4,
    iconName: "Leaf",
    badge: "Zero Emission",
  },
  {
    id: "uber-xl",
    name: "Premier SUV / XL",
    category: "suv",
    brandTag: "Spacious",
    tagColor: "text-zinc-300",
    tagBg: "bg-zinc-800/80 border-zinc-700/60",
    description: "Spacious 6-passenger vehicle ideal for families & airport luggage",
    baseFare: 160,
    perKmRate: 27,
    perMinuteRate: 3,
    etaMinutes: 6,
    capacity: 6,
    iconName: "Truck",
    badge: "6 Seats",
  },
];

export const POPULAR_LOCATIONS: PopularLocation[] = [
  {
    id: "loc-1",
    name: "Kempegowda Int'l Airport (BLR T1 & T2)",
    area: "Devanahalli, Airport Expressway",
    type: "airport",
    distanceKm: 34.2,
  },
  {
    id: "loc-2",
    name: "Indiranagar 100ft Road Metro",
    area: "Indiranagar Stage 2, Metro Line",
    type: "transit",
    distanceKm: 4.8,
  },
  {
    id: "loc-3",
    name: "Koramangala Sony World Junction",
    area: "80ft Road, Koramangala 4th Block",
    type: "techpark",
    distanceKm: 6.5,
  },
  {
    id: "loc-4",
    name: "Manyata Tech Park (Gate 1 & 2)",
    area: "Outer Ring Road, Hebbal",
    type: "techpark",
    distanceKm: 14.1,
  },
  {
    id: "loc-5",
    name: "Whitefield ITPL Main Gate",
    area: "International Tech Park, Whitefield",
    type: "techpark",
    distanceKm: 16.4,
  },
  {
    id: "loc-6",
    name: "Bengaluru City Central Railway Station",
    area: "Majestic Transit Hub",
    type: "transit",
    distanceKm: 8.2,
  },
  {
    id: "loc-7",
    name: "Electronic City Phase 1 Toll Plaza",
    area: "Elevated Expressway, Hosur Road",
    type: "techpark",
    distanceKm: 19.4,
  },
];

export const RENTAL_PACKAGES = [
  { id: "pkg-1", duration: "1 Hour", distance: "10 km", price: 299, desc: "Quick business errands and rapid multi-stop visits" },
  { id: "pkg-2", duration: "2 Hours", distance: "20 km", price: 549, desc: "Doctor consultations and consecutive client meetings" },
  { id: "pkg-3", duration: "4 Hours", distance: "40 km", price: 999, desc: "City business rounds and multi-destination itinerary", popular: true },
  { id: "pkg-4", duration: "8 Hours", distance: "80 km", price: 1899, desc: "Dedicated full-day car with professional chauffeur" },
  { id: "pkg-5", duration: "12 Hours", distance: "120 km", price: 2699, desc: "Extended corporate engagement and evening logistics" },
];

export const OUTSTATION_ROUTES = [
  { from: "Bengaluru", to: "Mysuru Heritage Corridor", distance: "145 km", time: "2h 45m", sedanPrice: 2450, suvPrice: 3500 },
  { from: "Bengaluru", to: "Coorg Hill Retreat", distance: "260 km", time: "5h 15m", sedanPrice: 4200, suvPrice: 5800 },
  { from: "Bengaluru", to: "Ooty Mountain Valley", distance: "275 km", time: "5h 45m", sedanPrice: 4600, suvPrice: 6300 },
  { from: "Bengaluru", to: "Tirupati Balaji Express", distance: "250 km", time: "4h 30m", sedanPrice: 3900, suvPrice: 5400 },
];

export const AVAILABLE_COUPONS = [
  { code: "MOBILITY50", discountPercent: 50, maxDiscount: 60, desc: "50% off up to ₹60 on Bike & Auto trips" },
  { code: "FIRST30", discountPercent: 30, maxDiscount: 100, desc: "30% off up to ₹100 on Mini or Sedan trips" },
  { code: "CORP20", discountPercent: 20, maxDiscount: 80, desc: "20% off on all Executive rides" },
];

export const MOCK_CITIES = ["Bengaluru", "Delhi NCR", "Mumbai", "Hyderabad", "Chennai", "Kolkata", "Pune", "Ahmedabad"];
